package com.segob.silverjuridico.model;
// Generated 5/12/2018 10:13:14 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Decretos generated by hbm2java
 */
public class Decretos  implements Serializable {
    
     private int id_decreto;
     private int numero_ley;
     private String texto_decreto;
     private String enlace_decreto;

    public Decretos() {
    }

    public Decretos(int id_decreto, int numero_ley, String texto_decreto, String enlace_decreto) {
        this.id_decreto = id_decreto;
        this.numero_ley = numero_ley;
        this.texto_decreto = texto_decreto;
        this.enlace_decreto = enlace_decreto;
    }

    public int getId_decreto() {
        return id_decreto;
    }

    public void setId_decreto(int id_decreto) {
        this.id_decreto = id_decreto;
    }

    public int getNumero_ley() {
        return numero_ley;
    }

    public void setNumero_ley(int numero_ley) {
        this.numero_ley = numero_ley;
    }

    public String getTexto_decreto() {
        return texto_decreto;
    }

    public void setTexto_decreto(String texto_decreto) {
        this.texto_decreto = texto_decreto;
    }

    public String getEnlace_decreto() {
        return enlace_decreto;
    }

    public void setEnlace_decreto(String enlace_decreto) {
        this.enlace_decreto = enlace_decreto;
    }

   



}


